

```{r setup, include=FALSE}
a <- scan("bible.txt",what="character",skip=104) ## skip contents
n <- length(a)
a <- a[-((n-2886):n)] ## strip license
a <- a[-grep("[0123456789]:[0123456789]",a)] ## strip out verse numbers
a=iconv(a,'WINDOWS-1252','UTF-8')
```

## 4 



```{r q4}
split_punct=function(punct_mark,l)
{
position=grep(punct_mark,l) #find the index that contains punctuations marks; return index
x=rep("",length(l)+length(position))  #create a empty x, put strings in it

iis<-position+1:length(position) #indice to put the marks
x[iis]<-substr(l[position],nchar(l[position]),nchar(l[position])) 
y=gsub(punct_mark,"",l) #delete all the marks
x[-iis]<-y


return(x)
}
```

## 5
```{r }
pm=',|\\.|;|:|!|\\?'
a_m=split_punct(pm,a) #a_m is the new list with character and marks individually
```


##6
```{r}
#remove punctuations from txt
a_c=gsub(pm,'',a)
#(a)
lowered_a=tolower(a_c)
unique_word=unique(lowered_a)
#(b)
u_index=match(lowered_a,unique_word)
#(c)
u_n=tabulate(u_index)
#(d)
threshold=u_n[rank(u_n,ties.method = 'random')==length(u_n)-500]
#(e)
b=unique_word[u_n>160]
```   



##7  b is the most commonly words 500.
```{r}
#a
 c1= match(lowered_a,b)# if it is common words over unique word list

#b
  #three column matrix empty
 
 c2=c1[-1] #index of common words
 
 c3=c2[-1]  #t1+1

 Triplet=cbind(c1,c2,c3)
 #c
 sum_of_rows<-rowSums (Triplet,na.rm = FALSE, dims = 1)
 matrix=Triplet[!is.na(sum_of_rows),1:3]
 #d
 T=array(0,c(499,499,499))
 for (i in 1:length(matrix[,1])){
    T[matrix[i,1],matrix[i,2],matrix[i,3]]=T[matrix[i,1],matrix[i,2],matrix[i,3]]+1}
 #e
 
 #f
 A=matrix(0,499,499)
 for(j in 1:length(matrix[,1])){
   A[matrix[j,1],matrix[j,2]]=A[matrix[j,1],matrix[j,2]]+1
   A[matrix[j,2],matrix[j,3]]=A[matrix[j,2],matrix[j,3]]+1
 }
 S=u_n[u_n>160]
```






##8
```{r}
Bible_simulation=function(T,A,S,b,n)
  {
  simu_index=rep(0,n)
  size=length(b)
  simu_index[1:2]=sample(size,2,prob=S)
  for (i in 3:n)
    {
      if (sum(T[simu_index[i-2],simu_index[i-1],]!=0))
      {
          simu_index[i]=sample(size,1,prob=T[simu_index[i-2],simu_index[i-1],])
      }
      else if(sum(A[simu_index[i-1],1])!=0)
      {
          simu_index[i]=sample(size,1,prob=A[i-1,])
      }
      else
      {
          simu_index[i]=sample(size,1,prob=S)
      }
  } 
  simu_txt=b[simu_index]
  return(simu_txt)
}
Markov_bible=Bible_simulation(T,A,S,b,50)
bible_in_order= paste(Markov_bible,collapse=' ')
```

##9
```{r}
random_bible=paste(sample_S=sample(b,50,prob=S),collapse=' ')

```

##10
```
```
